### ISSUE TITLE
Uncaught ModuleNotFoundError: No module named 'sklearn'


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [folini96/Cluster-Analysis-plugin#2]
Impossibile caricare il plugin 'Cluster-Analysis-plugin-main' a causa di un errore chiamando il metodo classFactory()
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\Cluster-Analysis-plugin-main\__init__.py", line 35, in classFactory
    from .cluster_analysis import ClusteringMain
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\Cluster-Analysis-plugin-main\cluster_analysis.py", line 32, in <module>
    from .cluster_analysis_dialog import ClusteringMainDialog
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\Cluster-Analysis-plugin-main\cluster_analysis_dialog.py", line 35, in <module>
    from sklearn.preprocessing import StandardScaler, MinMaxScaler
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'sklearn'

```
Cluster-Analysis-plugin-main 1.0.1, QGIS 3.28.4-Firenze on Windows 10

**Comment by folini96** [comment]
From the error, it looks like the scikit-learn library is missing in Python. Did you follow the instructions (which can be found in ReadMe) to add the necessary libraries before installing the plugin?
